name: drug_alarm
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_local_notifications: ^1.4.4+2
  intl: ^0.16.1
  sqflite: any
  path_provider: any
  android_alarm_manager: ^0.4.5+11
  shared_preferences: ^0.5.8
  android_intent: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/methotrexate.png
    - assets/images/alendronate.jpeg
    - assets/images/background.jpg
    - assets/icons/medicine.png
    - assets/reminder_database.db

